sources:
  linear:
    # how can I restrict a source to only one resource?
    type: lake.src.pipelines.linear.source.linear

destinations:
  warehouse:
    type: bigquery
    credentials: # -> injected via env variables

datasets:
  linear:

pipelines:
  linear:
    source: linear
    destination: warehouse
    dataset_name: linear
    progress: log

profiles:
  prod:
    destinations:
      bq:
        type: bigquery
        credentials: # injected via env variables
    sources:
      linear:
        start_date: "2024-11-01"
    runtime:
      log_level: INFO
  dev:
    destinations:
      warehouse:
        type: filesystem
        bucket_url: ${tmp_dir}
    sources:
      linear:
        start_date: "2024-11-01"
    runtime:
      log_level: DEBUG
    normalize:
      data_writer:
        disable_compression: TRUE
